# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    });
  };
  picom = {
    pname = "picom";
    version = "44b4970f70d6b23759a61a2b94d9bfb4351b41b1";
    src = fetchFromGitHub ({
      owner = "ibhagwan";
      repo = "picom";
      rev = "44b4970f70d6b23759a61a2b94d9bfb4351b41b1";
      fetchSubmodules = false;
      sha256 = "0iff4bwpc00xbjad0m000midslgx12aihs33mdvfckr75r114ylh";
    });
  };
}
